name: V2_Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  HiN-VPN:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ù…Ø¬ÙˆØ² Ù†ÙˆØ´ØªÙ† Ø¨Ø±Ø§ÛŒ GITHUB_TOKEN
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ú©Ù„ ØªØ§Ø±ÛŒØ®Ú†Ù‡ Ù…Ø®Ø²Ù† Ø±Ø§ Ø¯Ø±ÛŒØ§ÙØª Ù…ÛŒâ€ŒÚ©Ù†Ø¯

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Debug Files and Directories
        run: |
          pwd
          ls -la .
          cat source.conf || echo "source.conf not found or empty"
          mkdir -p subscription/normal subscription/base64 subscription/hiddify
          mkdir -p subscription/source/normal subscription/source/base64 subscription/source/hiddify
          ls -la subscription/

      - name: Execute PHP Script
        run: |
          php base.php
          git config --global user.email "yebekhe@gmail.com"
          git config --global user.name "yebekhe"
          git add -A
          git commit -m "ğŸš€ Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main # ÙØ±Ø¶ Ø¨Ø± Ø§ÛŒÙ† Ø§Ø³Øª Ú©Ù‡ Ø´Ø§Ø®Ù‡ Ø§ØµÙ„ÛŒ main Ø§Ø³Øª
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
